config/routes.rb
FetchLook::Application.routes.draw do
  devise_for :admins

  resources :sources, only: [ :index ] do
    resources :posts, only: [:index, :show, :update ] do
      post 'moderate'
      post 'select_image'
    end
  end

  root :to => 'sources#index'

end

app/models/admin.rb
class Admin
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""
  
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
end

app/models/image.rb
class Image
  include Mongoid::Document

  embedded_in :post

  field :src, type: String

  validates :src, presence: true, uniqueness: true
end

app/models/post.rb
class Post
  include Mongoid::Document

  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h

  mount_uploader :look_image, LookImageUploader

  after_update :crop_image_look

  belongs_to :source
  embeds_many :images

  field :url, type: String
  field :published, type: Time

  validates :url, :published, presence: true
  validates_uniqueness_of :url

  def crop_image_look
    look_image.recreate_versions! if crop_x.present?
  end

  state_machine initial: :standby do

    event :look_created do
      transition :in_line => :created
    end

    event :get_in_line do
      transition :standby => :in_line
    end

    event :reject do
      transition :standby => :rejected
    end

    event :put_on_standby do
      transition [ :rejected, :in_line ] => :standby
    end

  end

end

app/models/source.rb
class Source 
  include Mongoid::Document

  has_many :posts

  field :title, type: String
  field :category, type: String
  field :feed_url, type: String

  validates :category, :title, :feed_url, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_admin!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController 

  def index
    @source = Source.find(params[:source_id])
    @posts = @source.posts.order_by(state: -1, published: -1)
  end

  def show
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(params[:post])
      redirect_to source_post_path(@post.source, @post)
    end
  end

  def moderate
    @post = Post.find(params[:post_id])
    case params[:state]
    when 'Get in line'
      CreateLook.perform_at(10.seconds.from_now,params,@post.id)
      @post.get_in_line
    when 'Reject'
      @post.reject
    when 'Undo Reject'
      @post.put_on_standby
    end
    if @post.save!
      redirect_to source_posts_path(@post.source_id)
    else
      #TODO
    end
  end

end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController

  def index
    @sources = Source.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title FetchLook
  =stylesheet_link_tag  'application', media: :all
  =javascript_include_tag 'applications' 
  =csrf_meta_tags 
  %meta{ name: :viewport, content: 'width=device-width', :'initial-scale' => '1.0' }
%body
  =link_to 'Logout', destroy_admin_session_path, method: :delete, class: 'btn btn-danger btn-logout'
  %div.page-header.well
    %div.container
      %h1
        Hello
        %i
          -if current_admin
            =link_to current_admin.email, '/'
          -else
            =link_to 'Login', new_admin_session_path
        %small
          You have 
          %span.badge.badge-info
            =Post.where(state: 'standby').all.count
          posts to resolve
  %div.row
    %div.span4  
      %div.well
        =render partial: 'shared/sources_list', :locals => { sources:  Source.all }
    %div.span8
      =yield

app/views/posts/crop.html.haml
%h1 Welcome to Crop!
%div.crop-area
  =image_tag @post.look_image, id: 'cropbox'

%div.crop-preview.well
  %h2 Preview
  %div{:style => "width:100px; height:100px; overflow:hidden;"}
    = image_tag @post.look_image.url, :id => "preview"

= form_for [ @post.source, @post ] do |f|
  - %w(x y w h).each do |attribute|
    = f.hidden_field "crop_#{attribute}"
  .actions
    = f.submit 'Crop It !', class: 'btn btn-primary'

app/views/posts/index.html.haml
=render partial: 'shared/back_foward_nav', :locals => { path: sources_path }
%ol.posts-list
  -@posts.collect do |post|
    %li
      =link_to post.url.gsub(/http:\/\/|www./,''), source_post_path(post.source_id,post.id), class: post.state

app/views/posts/show.html.haml
= render partial: 'shared/back_foward_nav', :locals => { path: source_posts_path }

- if @post.look_image.url
  - if @post.state == 'standby'
    %div.preview.well
      = image_tag @post.look_image.adjusted.url, class: 'img-preview'
      =form_tag(source_post_moderate_path(@post.source_id,@post.id), id:'submit-look')  do
        %fieldset.occasions
          %legend Occasions
          - [ 'Casual Day Out', 'Casual Night Out', 'Beachwear', 'Sportwear', 'Black-tie', 'Work', 'Day Party', 'Evening Party' ].map do |occasion|
            %label
              %input{ type: :checkbox, name: 'occasions[]', value: occasion }
              =occasion
        %fieldset.garments
          %legend
            Garments
            - [ 'Dresses', 'Blouses', 'T-Shirts', 'Sweaters / Cardigans', 'Jackets / Blazers', 'Skirts', 'Shorts', 'Pants', 'Denim', 'Print', 'Animal Print', 'Boot', 'Stripes', 'Leather', 'Fur', 'Tank top', 'Tricot', 'Check', 'Ton Sur Ton', 'Floral'].map do |garment|
              %label
                %input{ type: :checkbox, name: 'garments[]', value: garment }
                =garment
        %input{ type: :submit, name: 'state', value: 'Get in line', class: [ 'btn', 'btn-success' ] }
      - unless @post.state == 'created'
        = form_for [ @post.source, @post ] do |f|
          = f.check_box :remove_look_image, checked: true, class: 'discart-image'
          = f.submit 'Discart Image !', class: [ 'btn btn-danger']
      %div.clearfix
  - elsif @post.state == 'in_line'
    %h2 Look watting in line :
    %p 
      Not working ?
      = form_for [ @post.source, @post ] do |f|
        = f.check_box :remove_look_image, checked: true, class: 'discart-image'
        = f.submit 'try again'
        = f.hidden_field 'state', value: 'standby'
    = image_tag @post.look_image.thumb.url if @post.look_image
  - elsif @post.state == 'created'
    = 'created :'
    = image_tag @post.look_image.thumb.url if @post.look_image


.btn-group.post-actions
  =form_tag(source_post_moderate_path(@post.source_id,@post.id)) do
    - if @post.state == 'standby' and !@post.look_image.file
      %input.btn.btn-danger{ type: :submit, name: 'state', value: 'Reject' }

= 'This Post has no images !' if @post.images.empty?

- unless @post.look_image.url
  %div.imgs-select-container
    %ul.thumbnails
      - @post.images.collect do |image|
        %li.span4
          %a.thumbnail.amp-look{ href: '#'}
            = image_tag image.src, id: image._id

/ Crop Holder
#crop-holder.well
  %h3
    Crop it! or
    %button.btn.btn-info.close-crop Pick another image
  %div.crop-area
    %img.look-img#cropbox
  = form_for [ @post.source, @post ] do |f|
    - %w(x y w h).each do |attribute|
      = f.hidden_field "crop_#{attribute}"
    = f.hidden_field 'remote_look_image_url'
    = f.hidden_field 'state', value: 'standby'
    .actions
      = f.submit 'Crop It !', class: 'btn btn-primary'

app/views/shared/_back_foward_nav.html.haml
%ul.pager
  %li.previous
    =link_to '← Back', path

app/views/shared/_sources_list.html.haml
%ul.nav.nav-tabs.nav-stacked.main-nav
  %li.nav-header Sources
  -sources.collect do |source|
    %li
      %span.badge
        =source.posts.map(&:state).select{|v| v =~ /standby/}.count
      =link_to source.title, [source, :posts]

app/views/sources/index.html.haml
%h1 Pick a sources and have fun !
%h2 Some stats for you:
%ul
  %li
    Sources number:
    %span.badge
      = Source.count
  %li
    Posts do resolve:
    %span.badge.badge-info
      = Post.where(state: 'standby').count
  %li
    Looks Created:
    %span.badge.badge-success
      = Post.where(state: 'created').count
  %li
    In line posts:
    %span.badge.badge-warning
      = Post.where(state: 'in_line').count
  %li
    Rejected posts:
    %span.badge.badge-important
      = Post.where(state: 'rejected').count